server: 
    port: 8200
    
spring: 
    application: 
        name: dubbo-provider

dubbo: 
    application:
        name: dubbo-provider
    protocol:
        name: dubbo
        port: 20880
    registry: 
        address: zookeeper://192.168.58.100:2181
    